# -*- coding: utf-8 -*-

import os
import random

import numpy as np

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable
from feedforward import FeedForward


class Generator(nn.Module):
    """Generator with self attention"""

    def __init__(self, vocab_size, hidden_dim, embedding_dim, num_layers, batch_size, seq_len, use_cuda, mode='word', start_token=0):
        super(Generator, self).__init__()
        self.hidden_dim = hidden_dim
        self.num_layers = num_layers
        self.use_cuda = use_cuda
        self.start_token = start_token
        self.seq_len = seq_len
        self.batch_size = batch_size
        self.vocab_size = vocab_size

        # Define embeddings
        self.emb = nn.Embedding(vocab_size, embedding_dim)

        if mode == "char":
            if vocab_size == embedding_dim:
                # One hot encodings
                self.emb.weight.data = torch.eye(vocab_size)
                self.emb.weight.requires_grad = False

        # Set number of layers to 1
        self.num_layers = 1

        # Create encoder
        self.lstm_enc = nn.LSTMCell(embedding_dim, hidden_dim)

        # Create decoder
        # Context dim == hidden dim
        self.lstm_dec = nn.LSTMCell(hidden_dim, hidden_dim)
        self.linear_dec = nn.Linear(hidden_dim, vocab_size)

        if self.use_cuda:
            self.lstm_dec = self.lstm_dec.cuda()
            self.lstm_enc = self.lstm_enc.cuda()

        # Init alignment model
        # We can precompute Ua * hj to save computation, CHECK PAPER
        # In our case we can store it until timestep I think
        self.alignment_model = FeedForward(hidden_dim + hidden_dim, hidden_dim, 1)
        if self.use_cuda:
            self.alignment_model = self.alignment_model.cuda()
        self.linear = nn.Linear(hidden_dim, vocab_size)
        self.softmax = nn.Softmax(dim=-1)
        self.log_softmax = nn.LogSoftmax(dim=-1)
        self.init_params()

    def forward(self, x):
        """
        Args:
            x: (batch_size, seq_len), sequence of tokens generated by generator
        """

        # Embeddings are (batch_size x seq_len x embedding_dim)
        emb = self.emb(x)
        h_t_enc, c_t_enc = self.init_hidden(self.batch_size)
        h_t_dec, c_t_dec = self.init_hidden(self.batch_size)
        annotations = list()
        outputs_dec = list()

        # Start with annotation vector
        context_t = Variable(torch.zeros((self.batch_size, self.hidden_dim)))
        if self.use_cuda:
            context_t = context_t.cuda()
        for i in range(self.seq_len):
            # Put in embeddings per timestep of (batch_size x embedding_dim) into the encoder
            h_t_enc, c_t_enc = self.lstm_enc(emb[:, i, :], (h_t_enc, c_t_enc))
            annotations.append(h_t_enc)
            # Could put it to 2?
            if i > 0:
                e_t = list()
                # Loop over all timesteps - 1 (preceding words)
                for j in range(i):
                    e_tj = self.alignment_model(torch.cat((h_t_dec, annotations[j]), 1))
                    e_t.append(e_tj)

                # Create alignment vector for all elements in the batch
                # (Batch_size x timestep - 1)
                e_t = torch.stack(e_t, 1).squeeze(2)
                a_t = self.softmax(e_t)

                # Stack hidden states up until timestep t
                # (Batch_size x hidden_size x timestep - 1)
                hidden_state = torch.stack(annotations, 2)[:, :, :-1]
                # Unpack tensor
                hidden_state = hidden_state.contiguous().view(self.batch_size, -1)

                a_t = a_t.repeat(1, self.hidden_dim)

                # Compute context vector for every example in the batch
                # (Batch_size x hidden_size)
                context_t = a_t * hidden_state

                # Get back to 3 dimensional tensor and sum over the time dimension for context vector
                context_t = a_t.view(self.batch_size, self.hidden_dim, i)
                context_t = torch.sum(context_t, dim=2)

            # Give context vector (batch_size x hidden_dim) as input to the decoder
            h_t_dec, c_t_dec = self.lstm_dec(context_t, (h_t_dec, c_t_dec))
            output_dec = self.log_softmax(self.linear_dec(h_t_dec))
            # Output is (batch_size x vocab_size)
            outputs_dec += [output_dec]

        # Reduce to ((batch_size x seq_len), vocab_size) for smooth log likelihood computation
        outputs = torch.stack(outputs_dec, 1).view(-1, self.vocab_size)

        return outputs

    def step(self, x, h, c):
        """
        Args:
            x: (batch_size,  1), sequence of tokens generated by generator
            h: (1, batch_size, hidden_dim), lstm hidden state
            c: (1, batch_size, hidden_dim), lstm cell state
        """
        emb = self.emb(x)
        self.lstm.flatten_parameters()
        output, (h, c) = self.lstm(emb, (h, c))
        pred = self.log_softmax(self.linear(output.view(-1, self.hidden_dim)))
        return pred, h, c

    def init_hidden(self, batch_size):
        h = Variable(torch.zeros((batch_size, self.hidden_dim)))
        c = Variable(torch.zeros((batch_size, self.hidden_dim)))
        if self.use_cuda:
            h, c = h.cuda(), c.cuda()
        return h, c

    def init_params(self):
        for param in self.parameters():
            param.data.uniform_(-0.05, 0.05)

    def sample(self, batch_size, seq_len, x=None):
        res = []
        flag = False  # whether sample from zero
        if x is None:
            flag = True
        if flag:
            x = Variable(self.start_token * torch.ones((batch_size, 1)).long())
        if self.use_cuda:
            x = x.cuda()
        h, c = self.init_hidden(batch_size)
        samples = []
        if flag:
            for i in range(seq_len):
                output, h, c = self.step(x, h, c)
                x = output.multinomial(1)
                samples.append(x)
        else:
            given_len = x.size(1)
            lis = x.chunk(x.size(1), dim=1)
            for i in range(given_len):
                output, h, c = self.step(lis[i], h, c)
                samples.append(lis[i])
            x = output.multinomial(1)
            for i in range(given_len, seq_len):
                samples.append(x)
                output, h, c = self.step(x, h, c)
                x = output.multinomial(1)
        output = torch.cat(samples, dim=1)
        return output
